apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fbdl-plugin
  labels:
    app: fbdl-plugin
spec:
  selector:
    matchLabels:
      app: fbdl-plugin
  template:
    metadata:
      labels:
        app: fbdl-plugin
    spec:
      containers:
      - name: fbdl-plugin
        image: quay.io/dfroehli/tpm-k8s-device-plugin:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
#        - name: dev-tpmrm
#          mountPath: /dev/tpmrm0
#          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      serviceAccountName: tpmaccess
      nodeSelector:
        tpm2: present
      volumes:
#      - name: dev-tpmrm
#        hostPath:
#          path: /dev/tpmrm0
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
